<?php

	$flaton_home = array(
		'slide1' => FLATON_PARENT_URL .'/images/slide1.png',
		'caption1' => __('caption','flaton'),
		'slide2' => FLATON_PARENT_URL .'/images/slide2.png',
		'caption2' => __('caption','flaton'),
        'service-main-title' => __('Our Services', 'flaton'),
        'service-sub-title' => __('Our Professional Solutions', 'flaton'),
    	'service-icon-1' => 'el-icon-bullhorn',
        'service-title-1' => __('Research', 'flaton'),
        'service-description-1' => __('<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>', 'flaton'),
        'service-icon-2' => 'el-icon-cogs',
        'service-title-2' => __('Usability', 'flaton'),
        'service-description-2' => __('<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.</p><ul>   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>   <li>Aliquam tincidunt mauris eu risus.</li>   <li>Vestibulum auctor dapibus neque.</li></ul>', 'flaton'),
        'service-icon-3' => 'el-icon-twitter',
        'service-title-3' => __('Design', 'flaton'),
        'service-description-3' => __('<h2>Header Level 2</h2><ol><li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li><li>Aliquam tincidunt mauris eu risus.</li></ol>', 'flaton'),
        'service-icon-4' => 'el-icon-group',
        'service-title-4' => __('Design', 'flaton'),
        'service-description-4' => 'html',
        'service-icon-5' => 'el-icon-digg',
        'service-title-5' => __('Design', 'flaton'),
        'service-description-5' => __('<h2>Header Level 2</h2><ol><li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li><li>Aliquam tincidunt mauris eu risus.</li></ol>', 'flaton'),
        'team' => __('<div class="eight columns team-col"><img src="http://localhost/flaton/wp-content/uploads/2014/04/team-mem1.gif" alt="" /><p>Many desktop publishing packages and we page editors now use Lorem Ipsum as their default model text, and a search for "lorem ipsum" will uncover many websites still in their infancy. Various verions have evolved over the years,sometimes by accident.<h5><strong>Feugiat Cursus</strong>Senior Manager</h5></div><div class="eight columns team-col"><img src="http://localhost/flaton/wp-content/uploads/2014/04/team-mem2.gif" alt="" /><p>Many desktop publishing packages and we page editors now use Lorem Ipsum as their default model text, and a search for "lorem ipsum" will uncover many websites still in their infancy. Various verions have evolved over the years,sometimes by accident.<h5><strong>Kelly Clarkson</strong>Art Director</h5></div><div class="eight columns team-col"><img src="http://localhost/flaton/wp-content/uploads/2014/04/team-mem3.gif" alt="" /><p>Many desktop publishing packages and we page editors now use Lorem Ipsum as their default model text, and a search for "lorem ipsum" will uncover many websites still in their infancy. Various verions have evolved over the years,sometimes by accident.<h5><strong>Chris Pontius</strong>Designer</h5></div><div class="eight columns team-col"><img src="http://localhost/flaton/wp-content/uploads/2014/04/team-mem4.gif" alt="" /><p>Many desktop publishing packages and we page editors now use Lorem Ipsum as their default model text, and a search for "lorem ipsum" will uncover many websites still in their infancy. Various verions have evolved over the years,sometimes by accident.<h5><strong>Bom Margera</strong>Code Ninja</h5></div><br class="clear" />', 'flaton'),
        'features' => __('<h2>Why Choose FlatOn</h2><p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced blow for those interested. Sections 1.10.32 and 1.10.33 from "De Finibus Bonorum et Malorum" by Cicero are also reproduced in their Exact original form, accompanied. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipusm has been the industry\'s standard dummy text ever since the...</p><p class="btn-more"><a href="#">Read More</a></p>', 'flaton'),
        'skill-heading' => __('Our Skills', 'flaton'),
        'skill-1' => __('Web Design','flaton'),
        'percentage-1' => '80',
        'skill-icon-1' => 'fa fa-bell',
        'skill-2' => __('Management','flaton'),
        'percentage-2' => '60',
        'skill-icon-2' => 'fa fa-camera',
        'skill-3' => __('Design','flaton'),
        'percentage-3' => '90',
        'skill-icon-3' => 'fa fa-recycle',
        'skill-4' => __('HTML &amp; CSS','flaton'),
        'percentage-4' => '100',
        'skill-icon-4' => 'fa fa-user',
        'skill-5' => __('WordPress','flaton'),
        'percentage-5' => '80',
        'skill-icon-5' => 'fa fa-play-circle',
        'extra-info' => __('<h2>Top Features</h2><img src="http://localhost/flaton/wp-content/uploads/2013/03/soworthloving-wallpaper-300x187.jpg" alt="" class="alignleft" /><h5><strong>Lorem ipsum dolor sit amet</strong></h5><p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p><p class="btn-more"><a href="#">Read More</a></p>', 'flaton'),
);